routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('teacher', 'TeacherController@index')->name('teacher');

Route::get('teacher/create', 'TeacherController@create')->name('create.teacher');

Route::post('teacher', 'TeacherController@store')->name('store.teacher');

Route::get('teacher/{id}', 'TeacherController@detail')->name('show.teacher');

Route::delete('teacher/{id}','TeacherController@destroy')->name('delete.teacher');

Route::resource('branch', 'BranchController');

Route::resource('subject', 'SubjectController');

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Teacher;

class Subject extends Model
{

    //allow mass assignment
    protected $fillable = ['name'];

    //relationship method
    public function teachers()
    {
        return $this->hasMany(Teacher::class);
    }
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subject;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subjects = Subject::orderBy('id', 'asc')->paginate(5);
        return view('subject.index', compact('subjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subject.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate request
        $this->validate($request, [
            'name' => 'required|unique:subjects'
        ]);

        //create data to table
        Subject::create([
            'name' => $request->name
        ]);

        //flash message
        session()->flash('success', 'Mata Pelajaran Berhasil Ditambahkan');

        //redirect to index
        return redirect(route('subject.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        return view('subject.create')->with('subject', $subject);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        //validate request
        $this->validate($request, [
            'name' => 'required|unique:subjects|alpha'
        ]);

        $subject->name = $request->name;
        $subject->save();

        session()->flash('success', 'Mata Pelajaran Berhasil Diperbarui');

        return redirect(route('subject.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subject $subject)
    {
        $subject->delete();

        session()->flash('success', 'Data Mata Pelajaran Berhasil Dihapus');

        return redirect(route('subject.index'));
    }
}

resources/views/subject/create.blade.php
@extends('layout.main')

@if(isset($subject))
  @section('title', 'SIAK | EDIT MATA PELAJARAN')
@else
  @section('title', 'SIAK | TAMBAH MATA PELAJARAN')
@endif

@section('content')

<div class="col-lg-8 mb-4 mx-auto">
    <div class="card mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-center">
          <h6 class="m-0 font-weight-bold text-primary" >
            {{isset($subject) ? 'EDIT MATA PELAJARAN' : 'TAMBAH MATA PELAJARAN'}}
          </h6>
        </div>
        <hr class="sidebar-divider my-0">
        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            @foreach($errors->all() as $error)
              {{$error}}
            @endforeach
          </div>
          @endif
          <form action="{{isset($subject) ? route('subject.update', $subject->id) : route('subject.store')}}" method="POST">
            @csrf
            @if(isset($subject))
              @method('PUT')
            @endif
            <div class="form-group">
              <input type="text" class="form-control" name="name" placeholder="Nama...."
              value="{{isset($subject) ? $subject->name : ''}}">
            </div>
            <hr class="sidebar-divider my-3">
            <button type="submit" class="btn btn-primary btn-sm">
              {{isset($subject) ? 'Perbarui' : 'Simpan'}}
            </button>
            <a href="{{ route('subject.index')}}" class="btn btn-primary btn-sm">Kembali</a>
            </div>
          </form>
        </div>
      </div>

</div>







@endsection

resources/views/subject/index.blade.php
@extends('layout.main')

@section('title', 'SIAK | MATA PELAJARAN')

@section('content')

<div class="col-lg-12 mb-4">
    <!-- Simple Tables -->
    <div class="card">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">DATA MATA PELAJARAN</h6>
        <a class="m-0 float-right btn btn-success btn-sm" href="{{ route('subject.create') }}">
            <i class="fas fa-plus"></i> Tambah Mata Pelajaran
        </a>
    </div>
    <hr class="sidebar-divider my-0">
    <div class="table-responsive">
        @if(session()->has('success'))
            <div class="alert alert-success" role="alert">
                {{session()->get('success')}}
            </div>
        @endif
        <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
            <th >No</th>
            <th >Nama</th>
            <th >Pilihan</th>
            </tr>
        </thead>
        <tbody>
            @if(count($subjects) != 0)
            @foreach($subjects as $index => $subject)
            <tr>
                <td>{{$index + $subjects->firstItem()}}</td>
                <td>{{$subject->name}}</td>
                <td>
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                        <a href="{{route('subject.edit', $subject->id)}}" class="btn btn-success btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="{{route('subject.destroy', $subject->id)}}" class="btn btn-danger btn-sm btn-delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
            @endforeach
            <form id="form-delete" method="POST" style="display: none">
                @csrf
                @method('DELETE')
            </form>
            @else
                <tr>
                    <td></td>
                    <td align="center">Tidak Ada Data</td>
                    <td></td>
                </tr>
            @endif
        </tbody>
        </table>
        <hr class="sidebar-divider my-0">
        <nav class="mt-4 d-flex justify-content-center">
            {{ $subjects->links() }}
        </nav>

    </div>
</div>
@endsection

@section('scripts')
<script>
    document.querySelectorAll('.btn-delete').forEach((button) => {
        button.addEventListener('click', function(event) {
            event.preventDefault()
            if (confirm("Are You Sure ?")) {
                let action = this.getAttribute('href')
                let form = document.getElementById('form-delete')
                form.setAttribute('action', action)
                form.submit()
            }
        })
    })
</script>
@endsection