routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('teacher', 'TeacherController@index')->name('teacher');

Route::get('teacher/create', 'TeacherController@create')->name('create.teacher');

Route::post('teacher', 'TeacherController@store')->name('store.teacher');

Route::get('teacher/{id}', 'TeacherController@detail')->name('show.teacher');

Route::delete('teacher/{id}','TeacherController@destroy')->name('delete.teacher');

Route::resource('branch', 'BranchController');

Route::resource('subject', 'SubjectController');

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Teacher;

class Branch extends Model
{
   //allow mass assignment
   protected $fillable = ['name'];

    //relationship method
    public function teachers()
    {
        return $this->hasMany(Teacher::class);
    }
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Branch;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = Branch::orderBy('id', 'asc')->paginate(5);
        return view('branch.index', compact('branches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branch.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate request
        $this->validate($request, [
            'name' => 'required|unique:branches'
        ]);

        //create data to table
        Branch::create([
            'name' => $request->name
        ]);

        //flash message
        session()->flash('success', 'Cabang Berhasil Ditambahkan');

        //redirect to index
        return redirect(route('branch.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Branch $branch)
    {
        return view('branch.create')->with('branch', $branch);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Branch $branch)
    {
        //validate request
        $this->validate($request, [
            'name' => 'required|unique:branches|alpha'
        ]);

        $branch->name  = $request->name;
        $branch->save();

        session()->flash('success', 'Cabang Berhasil Diperbarui');

        return redirect(route('branch.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Branch $branch)
    {
        $branch->delete();

        session()->flash('success', 'Data Cabang Berhasil Dihapus');

        return redirect(route('branch.index'));
    }
}

resources/views/branch/create.blade.php
@extends('layout.main')

@if(isset($branch))
  @section('title', 'SIAK | EDIT CABANG')
@else
  @section('title', 'SIAK | TAMBAH CABANG')
@endif

@section('content')

<div class="col-lg-8 mb-4 mx-auto">
    <div class="card mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-center">
          <h6 class="m-0 font-weight-bold text-primary">
            {{isset($branch) ? 'EDIT CABANG' : 'TAMBAH CABANG'}}
          </h6>
        </div>
        <hr class="sidebar-divider my-0">
        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            @foreach($errors->all() as $error)
              {{$error}}
            @endforeach
          </div>
          @endif
          <form action="{{ isset($branch) ? route('branch.update', $branch->id) : route('branch.store')}}" method="POST">
            @csrf
            @if(isset($branch))
              @method('PUT')
            @endif
            <div class="form-group">
              <input type="text" class="form-control" name="name" placeholder="Nama...."
              value="{{isset($branch) ? $branch->name : ''}}">
            </div>
            <hr class="sidebar-divider my-3">
            <button type="submit" class="btn btn-primary btn-sm">
              {{isset($branch) ? 'Perbarui' : 'Simpan'}}
            </button>
            <a href="{{ route('branch.index')}}" class="btn btn-primary btn-sm">Back</a>
            </div>
          </form>
        </div>
      </div>

</div>







@endsection

resources/views/branch/index.blade.php
@extends('layout.main')

@section('title', 'SIAK | CABANG')

@section('content')

<div class="col-lg-12 mb-4">
    <!-- Simple Tables -->
    <div class="card">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">DATA CABANG</h6>
        <a class="m-0 float-right btn btn-success btn-sm" href="{{ route('branch.create') }}">
            <i class="fas fa-plus"></i> Tambah Cabang
        </a>
    </div>
    <hr class="sidebar-divider my-0">
    <div class="table-responsive">
        @if(session()->has('success'))
            <div class="alert alert-success" role="alert">
                {{session()->get('success')}}
            </div>
        @endif
        <table class="table align-items-center table-flush">

        <thead class="thead-light">
            <tr>
            <th >No</th>
            <th >Nama Cabang</th>
            <th >Pilihan</th>
            </tr>
        </thead>
        <tbody>
            @if(count($branches) != 0)
            @foreach($branches as $index => $branch)
            <tr>
                <td>{{$index  + $branches->firstItem()}}</td>
                <td>{{$branch->name}}</td>
                <td>
                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                        <a href="{{route('branch.edit', $branch->id)}}" class="btn btn-success btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="{{route('branch.destroy', $branch->id)}}" class="btn btn-danger btn-sm btn-delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </td>
            </tr>
            @endforeach
                <form id="form-delete" method="POST" style="display: none">
                    @csrf
                    @method('DELETE')
                </form>
            @else
            <tr>
                <td></td>
                <td align="center">Tidak Ada Data</td>
                <td></td>
            </tr>
            @endif
        </tbody>
        </table>

        <nav class="mt-4 d-flex justify-content-center">
            {{ $branches->links() }}
        </nav>
    </div>
</div>
@endsection

@section('scripts')
<script>
    document.querySelectorAll('.btn-delete').forEach((button) => {
        button.addEventListener('click', function(event) {
            event.preventDefault()
            if (confirm("Are You Sure ?")) {
                let action = this.getAttribute('href')
                let form = document.getElementById('form-delete')
                form.setAttribute('action', action)
                form.submit()
            }
        })
    })
</script>
@endsection